-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Users"
(
    "UID" serial NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 ),
    "UserName" character varying(25) NOT NULL,
    "Pass" character(256) NOT NULL,
    "Email" character varying(50) NOT NULL,
    "Phone" character(10),
    "CreateDate" date,
    "LastSeen" date,
    CONSTRAINT "PK_UID" PRIMARY KEY ("UID")
);

COMMENT ON TABLE public."Users"
    IS 'Users go here';

COMMENT ON COLUMN public."Users"."UID"
    IS 'User ID, also PK';

COMMENT ON COLUMN public."Users"."CreateDate"
    IS 'When was user created';

COMMENT ON COLUMN public."Users"."LastSeen"
    IS 'When was user last seen';

CREATE TABLE IF NOT EXISTS public."Groups"
(
    "GID" serial NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 ),
    "UserID" integer,
    "CreateDate" date NOT NULL,
    "Admin" integer,
    CONSTRAINT "PK_GID" PRIMARY KEY ("GID")
);

COMMENT ON TABLE public."Groups"
    IS 'Groups go here';

COMMENT ON COLUMN public."Groups"."UserID"
    IS 'User ID, also FK';

COMMENT ON COLUMN public."Groups"."Admin"
    IS 'Who are the admins';

CREATE TABLE IF NOT EXISTS public."Conversations"
(
    "MID" bigint NOT NULL,
    "UserID" integer NOT NULL,
    "MSGID" integer NOT NULL,
    "Timestamp" date NOT NULL,
    "Title" character varying(50),
    CONSTRAINT "PK_MID" PRIMARY KEY ("MID")
);

COMMENT ON TABLE public."Conversations"
    IS 'Chats go here';

COMMENT ON COLUMN public."Conversations"."MID"
    IS 'Message ID, also PK';

COMMENT ON COLUMN public."Conversations"."MSGID"
    IS 'Message ID, also FK';

COMMENT ON COLUMN public."Conversations"."Timestamp"
    IS 'Message timestamp';

COMMENT ON COLUMN public."Conversations"."Title"
    IS 'Message Title, optional';

CREATE TABLE IF NOT EXISTS public."Messages"
(
    "MSGID" bigserial NOT NULL,
    "Message" character varying(250),
    "AuthID" integer,
    CONSTRAINT "PK_MSGID" PRIMARY KEY ("MSGID")
);

COMMENT ON TABLE public."Messages"
    IS 'Messages go here';

COMMENT ON COLUMN public."Messages"."MSGID"
    IS 'Message ID, also PK';

COMMENT ON COLUMN public."Messages"."Message"
    IS 'Message body, up to 250 symbols';

COMMENT ON COLUMN public."Messages"."AuthID"
    IS 'User ID, also FK';

CREATE TABLE IF NOT EXISTS public."Calls"
(
    "CID" bigserial NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 ),
    "InProgress" boolean NOT NULL DEFAULT false,
    "CallerUID" integer NOT NULL,
    CONSTRAINT "PK_CID" PRIMARY KEY ("CID")
);

COMMENT ON TABLE public."Calls"
    IS 'Calls go here';

COMMENT ON COLUMN public."Calls"."CID"
    IS 'Call ID, also PK';

COMMENT ON COLUMN public."Calls"."InProgress"
    IS 'Are we still in talking';

COMMENT ON COLUMN public."Calls"."CallerUID"
    IS 'Who called, also FK';

ALTER TABLE IF EXISTS public."Groups"
    ADD CONSTRAINT "FK_UID" FOREIGN KEY ("UserID")
    REFERENCES public."Users" ("UID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public."Conversations"
    ADD CONSTRAINT "FK_UID" FOREIGN KEY ("UserID")
    REFERENCES public."Users" ("UID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public."Messages"
    ADD CONSTRAINT "FK_AuthID" FOREIGN KEY ("AuthID")
    REFERENCES public."Users" ("UID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public."Calls"
    ADD CONSTRAINT "FK_CallerUID" FOREIGN KEY ("CallerUID")
    REFERENCES public."Users" ("UID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;

END;