-- Потребителя ни
CREATE USER "Avy" WITH ENCRYPTED PASSWORD 'toppass1';
ALTER USER "Avy" CREATEDB;

-- Базите данни
DROP DATABASE IF EXISTS "UsersDB";
CREATE DATABASE "UsersDB" WITH OWNER='Avy' ENCODING='UTF8' LC_COLLATE='en_US.UTF8' LC_CTYPE = 'en_US.UTF8';
DROP DATABASE IF EXISTS "ChatsDB";
CREATE DATABASE "ChatsDB" WITH OWNER='Avy' ENCODING='UTF8' LC_COLLATE='en_US.UTF8' LC_CTYPE = 'en_US.UTF8';
DROP DATABASE IF EXISTS "FilesDB";
CREATE DATABASE "FilesDB" WITH OWNER='Avy' ENCODING='UTF8' LC_COLLATE='en_US.UTF8' LC_CTYPE = 'en_US.UTF8';

-- Даваме * права на потребителя ни
GRANT ALL PRIVILEGES ON DATABASE UsersDB TO Avy;
GRANT ALL PRIVILEGES ON DATABASE ChatsDB TO Avy;
GRANT ALL PRIVILEGES ON DATABASE FilesDB TO Avy;

-- Правим таблиците във viber2-ERD.sql файла
-- Ако не работи: https://www.postgresql.org/docs/14/reference.html
